experiment:
  seed: 0
  description: Train GraphSAGE on Simulated 10K dataset

data:
  dataset_name: 'sss2-1b_1p'
  feature_name: 'cell_gene_counts'
  label_name: 'cell_types'
  graph_kwargs: {
                'coord_type': 'generic',
                'spatial_key': 'spatial',
                'delaunay': True,
                'radii': [],
                'delaunay_radius_union': False,
                'set_diag': True
                }
  data_directory_path: '/lustre/scratch126/cellgen/team361/DATASETS'
  overwrite: False
  transform_names: [
                  'NormalizeFeatures',
                  'RandomNodeSplit'
                  ]
  transform_kwargs: {
                    'norm_method': 'read_depth',
                    'val_ratio': 0.1,
                    'test_ratio': 0.1
                    }
  batch_idx: 0
  loader: 'neighbor'
  loader_kwargs: {
                  'num_neighbors': [25, 10],
                  'batch_size': 1024,
                  'num_workers': 4
                  }

model:
  name: 'GraphSAGE'
  model_params: {
                'encoder_name': 'SAGE_Encoder',
                'predictor_name': 'Linear',
                'hidden_channels': 256,
                'num_layers': 2,
                'dropout': 0.5
                }
  optimizer_params: {
                    'optimizer_name': 'adam',
                    'lr': 0.01,
                    'weight_decay': 0.0,
                    }
  loss_params: {
                'loss_names': ['cross_entropy'],
                'loss_kwargs': {'reduction': 'mean'}
                }
  task_params: {
                'task_name': 'multiclass',
                'task_kwargs': {}
                }

trainer:
  accelerator: 'gpu'
  monitor: 'val_acc'
  save_top_k: 1
  mode: 'max'
  save_last: True
  max_epochs: 10
  ckpt_path: 'best'