experiment:
  seed: 0
  mode: standalone

logging:
  root_log_dir: /lustre/scratch126/cellgen/team361/am84/VQNiche/reproducibility/logs
  log_model: false
  offline: true
  enabled: true

dataset:
  dataset_name: xhs1000-39b_1p
  adata_batch_idx:
    - 1
    - 2
  adata_fname:
    - adata_batch1.h5ad
    - adata_batch2.h5ad

  feature_name: cell_gene_counts

  graph_params:
    coord_type: generic
    spatial_key: spatial
    delaunay: false
    n_neighs: 8
    radius: null
    include_self_loop: true

  label_name: cell_types

  transform_names:
    - RandomNodeSplit
  transform_params:
    val_ratio: 0.1
    test_ratio: 0.1

  root_data_dir: /lustre/scratch126/cellgen/team361/DATASETS

datamodule:
  loader_name: NeighborLoader
  loader_params:
    batch_size: 128
  sampler_name: NeighborSampler
  sampler_params:
    num_neighbors: [25, 10]
  inference_params:
    sample_neighbors_for_inference: false

model:
  model_name: VQGraph
  encoder_name: VQGraph_Encoder
  attribute_decoder_name: LinearSoftmax
  predictor_name: Linear

  train_log_flags:
    log_similarity_stats: true
    log_codebook_utilization: true
    log_pearson_correlation: true

  encoder_params:
    graphconv_layer_name: SAGEConv
    hidden_channels: 32
    num_layers: 2
    act_first: true
    activation: relu
    norm: BatchNorm
    dropout: 0.1
    init_method: kaiming_uniform
    codebook_params:
        learnable_codebook: true
        num_codebooks: 1
        codebook_size: 256
        decay: 0.8
        eps: 0.00001
        kmeans_init: false
        kmeans_iters: 10
        sync_kmeans: true
        threshold_ema_dead_code: 0
        use_ddp: false
        sample_codebook_temp: 0.0

  optimizer_params:
    optimizer_name: adam
    lr: 0.005
    weight_decay: 0.0001

  loss_params:
    loss_names:
      # - cross_entropy
      # - mse_attribute_reconstruction
      - nb_attribute_reconstruction
      # - mse_adjacency_reconstruction
      # - mse_commit_loss
      # - mse_code_loss
    loss_kwargs:
      wt_cross_entropy: 1.0
      wt_attr_reconstr: 1.0
      wt_adj_reconstr: 1.0
      wt_commit: 1.0
      wt_code: 1.0

trainer:
  checkpoint_params:
    mode: max
    save_top_k: 1
    save_last: true
  max_epochs: 10
  enable_checkpointing: true
  ckpt_path: best