experiment:
  seed: 0
  mode: standalone

logging:
  root_log_dir: /lustre/scratch126/cellgen/team361/am84/VQNiche/reproducibility/logs
  log_model: false
  offline: true
  enabled: true

dataset:
  dataset_name: xhs1000-39b_1p
  adata_batch_idx:
    - 1
  adata_fname:
    - adata_batch1.h5ad

  feature_name: cell_gene_counts

  graph_params:
    coord_type: generic
    spatial_key: spatial
    delaunay: false
    n_neighs: 8
    radius: null
    include_self_loop: true

  label_name: cell_types

  transform_names:
    - SubsetHVG
    - RandomNodeSplit
  transform_params:
    n_genes: 1000
    val_ratio: 0.1
    test_ratio: 0.1

  root_data_dir: /lustre/scratch126/cellgen/team361/DATASETS

datamodule:
  loader_name: NeighborLoader
  loader_params:
    batch_size: 512
  sampler_name: NeighborSampler
  sampler_params:
    num_neighbors: [25, 10]
  inference_params:
    sample_neighbors_for_inference: false

model:
  model_name: GraphSAGE
  encoder_name: SAGEConv
  attribute_decoder_name: MLPSoftmax
  predictor_name: Linear

  train_log_flags:
    log_similarity_stats: false
    log_pearson_correlation: true
    
  encoder_params:
    mlp_params:
      hidden_channels: [900, 750]
      dropout: 0.1
      act: relu
      norm: batch_norm
    gnn_params:
      num_layers: 1
      hidden_channels: 600
      act_first: true
      activation: relu
      norm: BatchNorm
      dropout: 0.0
      init_method: kaiming_uniform

  attribute_decoder_params:
    mlp_params:
      hidden_channels: [600, 750]
      dropout: 0.1
      act: relu
      norm: batch_norm


  optimizer_params:
    optimizer_name: adam
    lr: 0.0005
    weight_decay: 0.001

  loss_params:
    loss_names:
      # - cross_entropy
      - nb_attribute_reconstruction
    loss_kwargs:
      wt_cross_entropy: 1.0
      wt_attr_reconstr: 1.0

trainer:
  checkpoint_params:
    mode: max
    save_top_k: 1
    save_last: true
  max_epochs: 20
  enable_checkpointing: true
  ckpt_path: best