experiment:
  seed: 0
  mode: standalone

logging:
  root_log_dir: /nfs/team361/am84/VQNiche/logs/
  # log_model: true
  # offline: false
  log_model: false
  offline: true
  enabled: true

dataset:
  dataset_name: xhs1021-15b_1p
  adata_batch_idx:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    # - 13

  root_data_dir: /lustre/scratch126/cellgen/lotfollahi/DATASETS

  gene_count_transform_names:
    - SubsetHVG
  gene_count_transform_params:
    n_genes: 1000

  graph_params:
    spatial_key: spatial
    delaunay: false
    n_neighs: 8
    radius: null

  feature_names:
    - X

  label_name: cell_types

  train_transform_names:
    - SpatialBatchSplit
  train_transform_params:
    region: [
          {
            x_min: 0,
            x_max: 1000,
            y_min: 0,
            y_max: 1000,
          },
          {
            x_min: 1000,
            x_max: 2000,
            y_min: 2000,
            y_max: 3000,
          },
          {
            x_min: 2000,
            x_max: 3000,
            y_min: 3000,
            y_max: 4000,
          }
      ]  
    train_batches:
      - 0
      - 1
      # - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
    val_batches: []
    test_batches:
      - 2
    xy_key: xy_coordinates

datamodule:
  loader_name: NeighborLoader
  loader_params:
    batch_size: 256
  sampler_name: NeighborSampler
  sampler_params:
    num_neighbors: [16, 16]
  inference_params:
    sample_neighbors_for_inference: false

model:
  model_name: VQNiche
  encoder_name: VQNiche_Encoder
  attribute_decoder_name: MLPSoftmax
  adjacency_decoder_name: MLP_AdjacencyDecoder
  predictor_name: Linear

  imputation_params:
    # mask_strategy: original
    mask_strategy: learnable_parameter
    base_mask_ratio: 0.3
    final_mask_ratio: 0.3
    warmup_epochs: 0
    deterministic_masking: false
    compute_mask_input_diversity: false
    mask_token_eps: 0.0001

  train_metrics_list:
    - codebook_utilization
    - pearson_1hop_nbr

  test_metrics_list:
    - codebook_utilization
    - pearson_cell_wise
    - pearson_1hop_nbr
    - mmd_1hop_nbr
    - mmd_pca_1hop_nbr
    - pearson_gene_wise
    - pearson_gene_wise_1hop_nbr

  encoder_params:
  
    gnn_name: SAGEConv

    mlp_params:
      hidden_channels: [600, 200]
      dropout: 0.1
      act: relu
      norm: null

    gnn_params:
      hidden_channels: 200
      num_layers: 3
      act_first: true
      activation: relu
      norm: null
      dropout: 0.1
      init_method: kaiming_uniform

    conditioning_params:
      condition_list:
        - rbf_distances
        # - relative_xy
        - cell_batch_id
        # - timepoint_id
      use_bias: true
      use_residual: false
      residual_weight: 0.2
      init_mode: identity

    # spatial_prior_params:
    #   spatial_prior_feature: rbf_distances
    #   hidden_channels: []
    #   act: relu

    vq_params:
      vq_name: VectorQuantize
      # VQ related params
      freeze_codebook: false # should always be false

      # EMA update related params
      use_cosine_sim: true
      ema_update: true # if true, learnable related stuff is ignored
      manual_ema_update: false
      threshold_ema_dead_code: 100
      manual_in_place_optimizer_update: false # must be false if ema_update is true
      learnable_codebook: false # must be false if ema_update is true

      # Learnable update related params
      # use_cosine_sim: false
      # learnable_codebook: true
      # straight_through: false
      # rotation_trick: true
      # in_place_codebook_optimizer: null
      # manual_in_place_optimizer_update: false
      # ema_update: false

      # codebook related params
      codebook_size: 5000
      heads: 1
      separate_codebook_per_head: false
      decay: 0.8
      eps: 0.00001
      kmeans_init: false
      kmeans_iters: 10
      sync_kmeans: true
      sample_codebook_temp: 0.0

      # commitment loss related params
      commitment_weight: 0.0
      commitment_use_cross_entropy_loss: false

      # codebook diversity loss related params
      codebook_diversity_loss_weight: 0.0
      codebook_diversity_temperature: 100.0

      # orthogonal loss related params
      orthogonal_reg_weight: 0.0
      orthogonal_reg_max_codes: null # apply to a random subset of codes
      orthogonal_reg_active_codes_only: false # apply only to actively used codes in the current batch

  attribute_decoder_params:
    # apply_conditioning: null # pre-MLP | in-MLP | None
    # apply_conditioning: pre-MLP # pre-MLP | in-MLP | None

    apply_conditioning: in-MLP # pre-MLP | in-MLP | None
    conditioning_params:
      condition_list:
        - rbf_distances
        # - relative_xy
        - cell_batch_id
        # - timepoint_id
      use_bias: true
      use_residual: false
      residual_weight: 0.2
      init_mode: identity

    mlp_params:
      hidden_channels: [600]
      dropout: 0.1
      act: gelu
      norm: layer_norm

  adjacency_decoder_params:
    out_channels: 600

    mlp_params:
      hidden_channels: [400]
      dropout: 0.2
      act: relu
      norm: layer_norm

  optimizer_params:
    optimizer_name: adam
    lr: 0.001
    weight_decay: 0.001
    mask_lr_scale: 2.0

  loss_params:
    loss_names:
      # - cross_entropy_loss
      # - mse_attribute_reconstruction_loss
      - nb_attribute_reconstruction_loss
      # - mse_adjacency_reconstruction_loss
      - bce_adjacency_reconstruction_loss
      # - ce_spatial_prior_loss
      - mse_commit_loss
      - mse_code_loss
      - mask_token_regularization
    loss_kwargs:
      # k_hop_nb_loss: 0
      k_hop_nb_loss: 1
      only_masked: false
      # only_masked: true
      edge_sampling_ratio: null
      use_pos_weight: true
      estimate_adj_kwargs:
        nonlinearity: sigmoid
        k: 8
      wt_cross_entropy: 1.0
      wt_attr_reconstr: 1.0
      wt_adj_reconstr: 1.0
      wt_joint_code_commit: 1.0
      wt_commit: 1.0
      wt_code: 1.0
      wt_mask_token_regularization: 1.0

trainer:
  monitor: train_pearson_1hop_nbr
  checkpoint_params:
    mode: max
    save_top_k: 1
    save_last: true
  max_epochs: 5
  enable_checkpointing: true
  ckpt_path: best