experiment:
  seed: 0
  mode: standalone

logging:
  root_log_dir: /nfs/team361/am84/VQNiche/logs/
  # log_model: true
  # offline: false
  log_model: false
  offline: true
  enabled: true

dataset:
  dataset_name: xhs1000-39b_1p
  adata_batch_idx:
    - 11
    - 12
    - 13
  adata_fname:
    - adata_batch11.h5ad
    - adata_batch12.h5ad
    - adata_batch13.h5ad

  root_data_dir: /lustre/scratch126/cellgen/lotfollahi/DATASETS

  gene_count_transform_names:
    - SubsetHVG
  gene_count_transform_params:
    n_genes: 1000

  graph_params:
    spatial_key: spatial
    delaunay: false
    n_neighs: 8
    radius: null

  feature_names:
    - X

  label_name: cell_types

  # train_transform_names:
  #   - RandomNodeSplit
  # train_transform_params:
  #   val_ratio: 0.4
  #   test_ratio: 0.4

  # train_transform_names:
  #   - SpatialNodeSplit
  # train_transform_params:
  #   test_region:
  #     x_min: 1000
  #     x_max: 2000
  #     y_min: 3000
  #     y_max: 3500
  #   val_region:
  #     x_min: 3000
  #     x_max: 4000
  #     y_min: 3000
  #     y_max: 3500
  #   xy_key: xy_coordinates

  train_transform_names:
    - SpatialBatchSplit
  train_transform_params:
    region:
      x_min: 4000
      x_max: 5000
      y_min: 3000
      y_max: 3500
    xy_key: xy_coordinates
    train_batches:
      - 11
    val_batches:
      - 12
    test_batches:
      - 13


datamodule:
  loader_name: NeighborLoader
  loader_params:
    batch_size: 256
  sampler_name: NeighborSampler
  sampler_params:
    num_neighbors: [16, 16]
  inference_params:
    sample_neighbors_for_inference: false

model:
  model_name: VQNiche
  encoder_name: VQNiche_Encoder
  attribute_decoder_name: MLPSoftmax
  adjacency_decoder_name: MLP_AdjacencyDecoder
  predictor_name: Linear

  train_metrics_list:
    - codebook_utilization
    - pearson_cell_wise
    # - pearson_1hop_nbr
    # - cas
    # - mlami
    # - gcs
    # - mmd_degree
    # - num_edges
    # - max_degree

  encoder_params:
    gnn_name: SAGEConv

    mlp_params:
      hidden_channels: [600, 200]
      dropout: 0.1
      act: relu
      norm: null

    gnn_params:
      hidden_channels: 200
      num_layers: 1
      act_first: true
      activation: relu
      norm: null
      dropout: 0.1
      init_method: kaiming_uniform

    conditioning_params:
      condition_list:
        - rbf_distances
      use_bias: true
      use_residual: false
      residual_weight: 0.0
      init_mode: dependence
      # s_gamma: 0.2
      # s_beta: 0.5

    vq_params:
      vq_name: VectorQuantize
      # VQ related params
      freeze_codebook: false # should always be false

      # EMA update related params
      use_cosine_sim: true
      # use_cosine_sim: false
      ema_update: true # if true, learnable related stuff is ignored
      manual_ema_update: false
      threshold_ema_dead_code: 20
      manual_in_place_optimizer_update: false # must be false if ema_update is true
      learnable_codebook: false # must be false if ema_update is true

      # Learnable update related params
      # use_cosine_sim: false
      # learnable_codebook: true
      # straight_through: false
      # rotation_trick: true
      # in_place_codebook_optimizer: null
      # manual_in_place_optimizer_update: false
      # ema_update: false

      # codebook related params
      codebook_size: 5000
      heads: 1
      separate_codebook_per_head: false
      decay: 0.8
      eps: 0.00001
      kmeans_init: false
      kmeans_iters: 10
      sync_kmeans: true
      sample_codebook_temp: 0.0

      # commitment loss related params
      commitment_weight: 0.0
      commitment_use_cross_entropy_loss: false

      # codebook diversity loss related params
      codebook_diversity_loss_weight: 0.0
      codebook_diversity_temperature: 100.0

      # orthogonal loss related params
      orthogonal_reg_weight: 0.0
      orthogonal_reg_max_codes: null # apply to a random subset of codes
      orthogonal_reg_active_codes_only: false # apply only to actively used codes in the current batch

  attribute_decoder_params:
    mlp_params:
      hidden_channels: [600]
      dropout: 0.1
      act: gelu
      norm: layer_norm

    conditioning_params:
      # generator_hidden: [32]
      condition_list:
        - rbf_distances
      use_bias: true
      use_residual: false
      residual_weight: 0.0
      init_mode: dependence
      # softplus_eps: 0.001
      # s_gamma: 0.2
      # s_beta: 0.5
      # tanh_cap_gamma: 0.2
      # tanh_cap_beta: 0.05

  adjacency_decoder_params:
    out_channels: 600

    mlp_params:
      hidden_channels: [400]
      dropout: 0.2
      act: relu
      norm: layer_norm

  optimizer_params:
    optimizer_name: adam
    lr: 0.001
    weight_decay: 0.001

  loss_params:
    loss_names:
      # - cross_entropy_loss
      # - mse_attribute_reconstruction_loss
      - nb_attribute_reconstruction_loss
      # - mse_adjacency_reconstruction_loss
      - bce_adjacency_reconstruction_loss
      # - mse_joint_code_commit_loss
      - mse_commit_loss
      - mse_code_loss
    loss_kwargs:
      edge_sampling_ratio: null
      use_pos_weight: true
      estimate_adj_kwargs:
        nonlinearity: sigmoid
        k: 8
      wt_cross_entropy: 1.0
      wt_attr_reconstr: 1.0
      wt_adj_reconstr: 1.0
      wt_joint_code_commit: 1.0
      wt_commit: 1.0
      wt_code: 1.0

trainer:
  checkpoint_params:
    mode: max
    save_top_k: 1
    save_last: true
  max_epochs: 5
  enable_checkpointing: true
  ckpt_path: best