experiment:
  seed: 0
  mode: standalone

logging:
  root_log_dir: /nfs/team361/am84/VQNiche/logs/
  log_model: false
  offline: true
  enabled: true

dataset:
  dataset_name: xhs1000-39b_1p
  adata_batch_idx:
    - 11
  adata_fname:
    - adata_batch11.h5ad

  root_data_dir: /lustre/scratch126/cellgen/lotfollahi/DATASETS

  gene_count_transform_names:
    - SubsetHVG
  gene_count_transform_params:
    n_genes: 1000

  graph_params:
    spatial_key: spatial
    delaunay: false
    n_neighs: 8
    radius: null

  feature_names:
      - X
      # - U_lm_eigvecs
      # - U_deepwalk
      # - U_gosh

  label_name: cell_types

  train_transform_names:
    - RandomNodeSplit
  train_transform_params:
    val_ratio: 0.1
    test_ratio: 0.1

datamodule:
  loader_name: NeighborLoader
  loader_params:
    batch_size: 128
  sampler_name: NeighborSampler
  sampler_params:
    num_neighbors: [25, 10]
  inference_params:
    sample_neighbors_for_inference: false

model:
  model_name: VanillaMLP
  encoder_name: MLP_Encoder
  attribute_decoder_name: MLPSoftmax
  adjacency_decoder_name: MLP_AdjacencyDecoder
  predictor_name: Linear

  train_metrics_list:
    - pearson_cell_wise
    - pearson_1hop_nbr
    - mmd_degree
    - mmd_eigenvalues
    - num_edges
    - max_degree

  encoder_params:
    mlp_params:
      hidden_channels: [900, 750]
      dropout: 0.1
      act: relu
      norm: null

  attribute_decoder_params:
    mlp_params:
      hidden_channels: [900]
      dropout: 0.1
      act: relu
      norm: null

  adjacency_decoder_params:
    out_channels: 600
    mlp_params:
      hidden_channels: []
      dropout: 0.1
      act: relu
      norm: null

  optimizer_params:
    optimizer_name: adam
    lr: 0.0005
    weight_decay: 0.00001

  loss_params:
    loss_names:
      # - cross_entropy_loss
      - nb_attribute_reconstruction_loss
      - mse_adjacency_reconstruction_loss
    loss_kwargs:
      estimate_adj_kwargs:
        nonlinearity: relu-clamp
        k: 8
      wt_cross_entropy: 1.0
      wt_attr_reconstr: 1.0
      wt_adj_reconstr: 1.0

trainer:
  checkpoint_params:
    mode: max
    save_top_k: 1
    save_last: true
  max_epochs: 10
  enable_checkpointing: true
  ckpt_path: best