experiment:
  seed: 0
  mode: standalone

logging:
  root_log_dir: /nfs/team361/am84/VQNiche/logs/
  log_model: false
  offline: true
  enabled: true

dataset:
  dataset_name: xhs1000-39b_1p
  adata_batch_idx:
    - 11
  adata_fname:
    - adata_batch11.h5ad

  root_data_dir: /lustre/scratch126/cellgen/lotfollahi/DATASETS

  gene_count_transform_names:
    - SubsetHVG
  gene_count_transform_params:
    n_genes: 1000

  graph_params:
    spatial_key: spatial
    delaunay: false
    n_neighs: 8
    radius: null

  feature_names:
      - X

  label_name: cell_types

  train_transform_names:
    - RandomNodeSplit
  train_transform_params:
    val_ratio: 0.1
    test_ratio: 0.1

datamodule:
  loader_name: NeighborLoader
  loader_params:
    batch_size: 256
  sampler_name: NeighborSampler
  sampler_params:
    num_neighbors: [16, 16]
  inference_params:
    sample_neighbors_for_inference: false

model:
  model_name: GraphSAGE
  encoder_name: SAGEConv
  attribute_decoder_name: MLPSoftmax
  adjacency_decoder_name: MLP_AdjacencyDecoder
  predictor_name: Linear

  train_metrics_list:
    - pearson_cell_wise
    - pearson_1hop_nbr
    - cas
    - mlami
    # - mmd_degree
    # - mmd_eigenvalues
    # - num_edges
    # - max_degree

  encoder_params:
    mlp_params:
      hidden_channels: [600, 200]
      dropout: 0.1
      act: relu
      norm: null
    gnn_params:
      num_layers: 3
      hidden_channels: 200
      act_first: true
      activation: relu
      norm: null
      dropout: 0.1
      init_method: kaiming_uniform

  attribute_decoder_params:
    use_xy_coordinates: false
    mlp_params:
      hidden_channels: [200, 600]
      dropout: 0.1
      act: relu
      norm: layer_norm

  adjacency_decoder_params:
    mlp_params:
      hidden_channels: [200, 600]
      dropout: 0.2
      act: relu
      norm: layer_norm

  optimizer_params:
    optimizer_name: adam
    lr: 0.0005
    weight_decay: 0.001

  loss_params:
    loss_names:
      # - cross_entropy_loss
      - nb_attribute_reconstruction_loss
      # - mse_adjacency_reconstruction_loss
      - bce_adjacency_reconstruction_loss
    loss_kwargs:
      edge_sampling_ratio: 1.0
      use_pos_weight: true
      estimate_adj_kwargs:
        nonlinearity: sigmoid
        k: 8
      wt_cross_entropy: 1.0
      wt_attr_reconstr: 1.0
      wt_adj_reconstr: 1.0

trainer:
  checkpoint_params:
    mode: max
    save_top_k: 1
    save_last: true
  max_epochs: 10
  enable_checkpointing: true
  ckpt_path: best