experiment:
  seed: 0
  name: "train_gnn"

logging:
  log_dir: '/lustre/scratch126/cellgen/team361/am84/VQNiche/logs'
  log_model: False
  offline: True
  # mode: 'disabled' 
  mode: 'enabled'

dataset:
  name: 'sss2-1b_1p'
  feature_name: 'cell_gene_counts'
  label_name: 'niche_types'
  graph_params: {
                'coord_type': 'generic',
                'spatial_key': 'spatial',
                'delaunay': True,
                'n_neighs': null,
                'radius': null,
                }
  data_directory_path: '/lustre/scratch126/cellgen/team361/DATASETS'
  overwrite: False
  transform_names: [
                  'NormalizeFeatures',
                  'RandomNodeSplit'
                  ]
  transform_params: {
                    'norm_method': 'read_depth',
                    'val_ratio': 0.1,
                    'test_ratio': 0.1
                    }

datamodule:
  batch_idx: 0
  loader_name: 'DefaultNodeLoader'
  # loader_name: 'NeighborLoader'
  loader_params:  {
                        'batch_size': 1024,
                        }
  sampler_name: 'NeighborSampler'
  sampler_params: {
                         'num_neighbors': [25, 10],
                        }
  inference_params: {
                    'use_full_graph_for_inference': True,
                    }

model:
  name: 'VQGraph'
  model_params: {
                'encoder_name': 'VQGraph_Encoder',
                'graphconv_layer_name': 'SAGEConv',
                'predictor_name': 'Linear',
                'hidden_channels': 64,
                'num_layers': 2,
                'dropout': 0.1
                }
  optimizer_params: {
                    'optimizer_name': 'adam',
                    'lr': 0.02,
                    'weight_decay': 0.0001,
                    } 
  loss_params: {
                'loss_names': [
                              'cross_entropy',
                              'vqgraph_attribute_reconstruction',
                              # 'vqgraph_adjacency_reconstruction',
                              'vqgraph_commitment_loss',
                              'vqgraph_codebook_loss'
                              ],
                'loss_kwargs': {
                                'reduction': 'mean',
                                'scaling_node_gamma': 0.1,
                                'scaling_edge_gamma': 0.1,
                                'commitment_weight': 0.25,
                                'codebook_reg_weight': 0.2,
                                }
                }
  task_params: {
                'task_name': 'multiclass',
                'task_kwargs': {}
                }
  inference_params: {
                    'inference_mode': 'batch-wise',
                    # 'inference_mode': 'layer-wise',
                    }


trainer:
  checkpoint_params: {
                  'mode': 'max',
                  'monitor': 'val_acc',
                  'save_top_k': 1,
                  'save_last': True,
                  }
  max_epochs: 10
  enable_checkpointing: True
  ckpt_path: 'best'