name: backbone_gnn
method: grid
run_cap: 3
metric:
    goal: minimize
    name: val_pearson_cell_wise
parameters:
  experiment.seed:
    values: [0]
  model.encoder_params.gnn_name:
    values: [SAGEConv, GATv2Conv, GINConv]
  trainer.max_epochs:
    values: [5]
