name: gnn
method: bayes
run_cap: 10
metric:
    goal: minimize
    name: val_loss
parameters:
  model.encoder_params.gnn_params.hidden_channels:
    values: [100, 200, 500, 600, 750]
  model.encoder_params.gnn_params.num_layers:
    values: [1]
  model.encoder_params.gnn_params.activation:
    values: [relu]
  model.encoder_params.gnn_params.norm:
    values: [BatchNorm, null]
  model.encoder_params.gnn_params.dropout:
    values: [0.0, 0.1, 0.2]
