name: vq
method: bayes
run_cap: 10
metric:
    goal: minimize
    name: val_loss
parameters:
  model.encoder_params.codebook_params.learnable_codebook:
    value: true
  model.encoder_params.codebook_params.num_codebooks:
    value: 1
  model.encoder_params.codebook_params.codebook_size:
    values: [32, 64, 128, 256, 512, 1000]
  model.encoder_params.codebook_params.decay:
    value: 0.01
  model.encoder_params.codebook_params.eps:
    value: 0.00001
  model.encoder_params.codebook_params.kmeans_init:
    value: false
  model.encoder_params.codebook_params.kmeans_iters:
    value: 10
  model.encoder_params.codebook_params.sync_kmeans:
    value: true
  model.encoder_params.codebook_params.threshold_ema_dead_code:
    value: 0
  model.encoder_params.codebook_params.use_ddp:
    value: false
  model.encoder_params.codebook_params.sample_codebook_temp:
    value: 0.0
