experiment:
  description: "Create Simulated 10K Dataset"
  
data:
  dataset_name: "sss2-1b_1p"
  feature_names: ["cell_gene_counts"]
  label_names: [
                "cell_types",
                "niche_types"
                ]
  graph_kwargs: {
                'coord_type': 'generic',
                'spatial_key': 'spatial',
                'delaunay': True,
                'radii': [27.5, 55.0],
                'delaunay_radius_union': True,
                'set_diag': True
                }
  data_directory_path: "/lustre/scratch126/cellgen/team361/DATASETS"
  pre_transform: null
  pre_filter: null
  overwrite: True