experiment:
  name: "in_memory_dataset_blob"
  description: "Create Simulated 10K Dataset"

logging:
  log_dir: "/lustre/scratch126/cellgen/team361/am84/VQNiche/logs"

dataset:
  name: "sss2-1b_1p"
  feature_names: ["cell_gene_counts"]
  label_names: [
                "cell_types",
                "niche_types"
                ]
  graph_kwargs: {
                'coord_type': 'generic',
                'spatial_key': 'spatial',
                'n_neighs_list': [10, 20, 30],
                'radius_list': [27.5, 55.0],
                'include_self_loop': True,
                }
  data_directory_path: "/lustre/scratch126/cellgen/team361/DATASETS"
  pre_transform: null
  pre_filter: null
  overwrite: True