experiment:
  name: in_memory_dataset_blob
  description: Simulated 10K Dataset

dataset:
  name: sss2-1b_1p

  feature_names: 
    - cell_gene_counts

  label_names: 
    - cell_types=cell_types
    - niche_types=niche_types

  graph_kwargs:
    coord_type: generic
    spatial_key: spatial
    n_neighs_list: 
      - 4
      - 7
      - 8
      - 10
      - 12
    radius_list:
      - 27.5
    include_self_loop: true

  data_directory_path: /lustre/scratch126/cellgen/team361/DATASETS

  pre_transform: null

  pre_filter: null

  overwrite: true